//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.13 at 10:08:37 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://onlinetutorialspoint.com/generated", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hoangytm.soapconsumer.testbidding;
