//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.13 at 02:17:55 PM ICT 
//


package com.hoangytm.soapconsumer.testString;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hoangytm.soapconsumer.testString package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hoangytm.soapconsumer.testString
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sign }
     * 
     */
    public Sign createSign() {
        return new Sign();
    }

    /**
     * Create an instance of {@link SignResponse }
     * 
     */
    public SignResponse createSignResponse() {
        return new SignResponse();
    }

    /**
     * Create an instance of {@link CalculateVC }
     * 
     */
    public CalculateVC createCalculateVC() {
        return new CalculateVC();
    }

    /**
     * Create an instance of {@link CalculateVCResponse }
     * 
     */
    public CalculateVCResponse createCalculateVCResponse() {
        return new CalculateVCResponse();
    }

    /**
     * Create an instance of {@link SignFinal }
     * 
     */
    public SignFinal createSignFinal() {
        return new SignFinal();
    }

    /**
     * Create an instance of {@link SignFinalResponse }
     * 
     */
    public SignFinalResponse createSignFinalResponse() {
        return new SignFinalResponse();
    }

    /**
     * Create an instance of {@link SignLoc }
     * 
     */
    public SignLoc createSignLoc() {
        return new SignLoc();
    }

    /**
     * Create an instance of {@link SignLocResponse }
     * 
     */
    public SignLocResponse createSignLocResponse() {
        return new SignLocResponse();
    }

    /**
     * Create an instance of {@link PreviewSignature }
     * 
     */
    public PreviewSignature createPreviewSignature() {
        return new PreviewSignature();
    }

    /**
     * Create an instance of {@link PreviewSignatureResponse }
     * 
     */
    public PreviewSignatureResponse createPreviewSignatureResponse() {
        return new PreviewSignatureResponse();
    }

    /**
     * Create an instance of {@link GetCert }
     * 
     */
    public GetCert createGetCert() {
        return new GetCert();
    }

    /**
     * Create an instance of {@link GetCertResponse }
     * 
     */
    public GetCertResponse createGetCertResponse() {
        return new GetCertResponse();
    }

    /**
     * Create an instance of {@link Initial }
     * 
     */
    public Initial createInitial() {
        return new Initial();
    }

    /**
     * Create an instance of {@link InitialResponse }
     * 
     */
    public InitialResponse createInitialResponse() {
        return new InitialResponse();
    }

}
